### ISSUE TITLE
Player not loading and invisible during character selection and once a player select that character he spawns in a location 0,0,0 and the character is invisible

### ISSUE THREAD

**Issue by karthik-pitchai03** [thelindat/esx_multicharacter#41]
This happens when the players in the server reaches above 80 or something please lindat look into it im using esx legacy

**Comment by charankarthik** [comment]
![20210816132541_1](https://user-images.githubusercontent.com/64724676/129609781-84e5acf5-7e89-44e0-8648-a85d8d7abe4e.jpg)

![20210816132547_1](https://user-images.githubusercontent.com/64724676/129609800-05483dde-a707-4177-a2dc-e3d2b6c552ff.jpg)

Even I to have these problem

**Comment by thelindat** [comment]
"help me resolve an issue without any information or reproduction method while i post with two different github accounts"

**Comment by charankarthik** [comment]
For your kind note I hope so title says everything?

**Comment by karthik-pitchai03** [comment]
Hey lindat this can be seen only when 80 player joined the server, even i tried printing those user data everything is working but character is not loading but those character data like name, job, job grades everything works

**Comment by thelindat** [comment]
I had disabled issues thanks to you feeling the need to post the same issue 5 times using different accounts.

Since somebody _actually provided_ information related to the bug, a patch has been applied and seemingly resolves the issue. In the future, if you want something to happen then _don't spam useless garbage_.
