### ISSUE TITLE
hi ,thanks for solving my issues in linden inventory, have a new isues in multicahracter ifused in legacy after 100 people coming in no issues then peds are going into 0,0,0 coords in map default and  no eeors coming either tooo

### ISSUE THREAD

**Issue by muthurockon** [thelindat/esx_multicharacter#42]

**Comment by thelindat** [comment]
There's no need to write such a bloody long title.
Coordinates come from ESX, and if there isn't any coordinates then it falls back to the spawn location.

https://github.com/thelindat/esx_multicharacter/blob/master/client/main.lua#L263
```lua
RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(playerData, isNew, skin)
local spawn = playerData.coords or Config.Spawn
```
```lua
local playerPed = PlayerPedId()
FreezeEntityPosition(playerPed, true)
SetEntityCoords(playerPed, spawn.x, spawn.y, spawn.z-1.3, true, false, false, false)
SetEntityHeading(playerPed, spawn.heading)
```

I can only assume the issue is due to lag, like the other guy reporting the problem who has a server running at with 10ms CPU times. I can try implementing some of the logic from spawnmanager, but not everything is needed as the player and model have already been loaded.

I have seen similar issues occur on other poorly optimised servers when using other multicharacters (such as MF) where the entire city has no collision, but nothing would cause a player to spawn at 0,0,0

```lua
RequestCollisionAtCoord(spawn.x, spawn.y, spawn.z)

-- spawn the player
local ped = PlayerPedId()

-- V requires setting coords as well
SetEntityCoordsNoOffset(ped, spawn.x, spawn.y, spawn.z, false, false, false, true)

NetworkResurrectLocalPlayer(spawn.x, spawn.y, spawn.z, spawn.heading, true, true, false)

-- gamelogic-style cleanup stuff
ClearPedTasksImmediately(ped)
--SetEntityHealth(ped, 300) -- TODO: allow configuration of this?
RemoveAllPedWeapons(ped) -- TODO: make configurable (V behavior?)
ClearPlayerWantedLevel(PlayerId())



local time = GetGameTimer()

while (not HasCollisionLoadedAroundEntity(ped) and (GetGameTimer() - time) < 5000) do
    Citizen.Wait(0)
end
```

**Comment by muthurockon** [comment]
and further the character is also not loading when the server strength reaches 100 ,pls neeed a solution , no error popoing up too

**Comment by thelindat** [comment]
I'm sick of idiots like you. Get out of my repo.
